name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Project set to Dev
        uses: w9jds/firebase-action@master
        if: github.ref == 'refs/heads/dev'
        with:
          args: use dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Project set to Prod
        uses: w9jds/firebase-action@master
        if: github.ref == 'refs/heads/main'
        with:
          args: use prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Build
        run: CI=false yarn run build

      - name: Deploy to Firebase Dev
        uses: w9jds/firebase-action@master
        if: github.ref == 'refs/heads/dev'
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Prod
        uses: w9jds/firebase-action@master
        if: github.ref == 'refs/heads/main'
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
